server/config/routes.rb
Rails.application.routes.draw do

  resources :latlongs

  
  root 'geocode#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

server/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

server/app/models/latlong.rb
class Latlong < ApplicationRecord
end

server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

server/app/controllers/geocode_controller.rb
class GeocodeController < ApplicationController
  def index
  end
end

server/app/controllers/latlongs_controller.rb
class LatlongsController < ApplicationController

    def index
		@latlongs = Latlong.all
    end
	
	def show
		@latlong = Latlong.find(params[:id])
		@tmpVar = '{ "name" : "John" }';
	end
	
	def new
	end

	def create
		#  render plain: params[:latlong].inspect
		@latlong = Latlong.new(latlong_params)
 
		@latlong.save
		redirect_to @latlong
	end

	private
		def latlong_params
			params.require(:latlong).permit(:lattitude, :longitude)
		end
end

server/app/helpers/address_helper.rb
module AddressHelper
end

server/app/helpers/application_helper.rb
module ApplicationHelper
end

server/app/helpers/geocode_helper.rb
module GeocodeHelper
end

server/app/helpers/latlong_helper.rb
module LatlongHelper
end

server/app/helpers/latlongs_helper.rb
module LatlongsHelper
end

server/app/views/geocode/index.html.erb
<h1>Geocode#index</h1>
<p>Find me in app/views/geocode/index.html.erb</p>

server/app/views/latlongs/index.html.erb
<h1>Listing articles</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @latlongs.each do |ll| %>
    <tr>
      <td><%= ll.lattitude %></td>
      <td><%= ll.longitude %></td>
      <td><%= link_to 'Show', latlong_path(ll) %></td>
    </tr>
  <% end %>
</table>

server/app/views/latlongs/new.html.erb
<h1> LatLongs view </h1>


<%= form_for :latlong, url: latlongs_path do |f| %>
  <p>
    <%= f.label :lattitude %><br>
    <%= f.text_field :lattitude %>
  </p>
 
  <p>
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

server/app/views/latlongs/show.html.erb
<p>
  <strong>Lattitude:</strong>
  <%= @latlong.lattitude %>
</p>
 
<p>
  <strong>Longitude:</strong>
  <%= @latlong.longitude %>
</p>

<p id=testString </p>
<script>
var newText = "<%= @tmpVar.to_s %>";
document.getElementById("testString").innerHTML = newText; 

</script>

server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Server</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>